org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.daemon=false

minecraft_version=1.21.1
neoforge_version=21.1.248

mod_id=eyrax_apothic_animals
mod_name=EYRAX-Apothic-Animals
mod_display_name=EYRAX Apothic Animals
mod_version=1.1.0
mod_group=com.eyrax.apothicanimals

apotheosis_version=8.7.0
apothic_attributes_version=2.10.0
placebo_version=9.9.2
patchouli_version=1.21-87-NEOFORGE
apothic_spawners_version=1.4.0
apothic_enchanting_version=1.6.0
